cloud:
  aws:
    credentials:
      access-key: ${s3_access_key}
      secret-key: ${s3_secret_key}
    region:
      static: ${s3_bucket_region}
    stack:
      auto: false

application:
  bucket:
    name: ${s3_bucket_name}

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: ${port}